name: YouTube AutoBot Pro Max

on:
  schedule:
    - cron: '0 */6 * * *'  # 6시간 간격 실행 (쿼터 관리)
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-24.04
    timeout-minutes: 120

    steps:
    - name: 코드 동기화
      uses: actions/checkout@v4

    - name: 시스템 설정
      run: |
        mkdir -p static/{videos,audio,logs}
        sudo apt-get install -y ffmpeg

    - name: 파이썬 환경
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 패키지 설치
      run: pip install -r requirements.txt

    - name: 실행 단계
      env:
        OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }}
        ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: python main.py --auto

