name: Auto Upload
on:
  schedule:
    - cron: "0 */6 * * *"  # 6시간 간격
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          sudo apt-get install ffmpeg -y
          pip install -r requirements.txt
          
      - name: Run Automation
        env:
          OPENAI_KEYS: ${{ secrets.OPENAI_KEYS }}
          ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.VOICE_ID }}
          GOOGLE_CID: ${{ secrets.GOOGLE_CID }}
          GOOGLE_CSECRET: ${{ secrets.GOOGLE_CSECRET }}
          GOOGLE_RTOKEN: ${{ secrets.GOOGLE_RTOKEN }}
          TREND_KEYWORDS: ${{ secrets.TRENDS }}
          DAILY_VIDEOS: ${{ secrets.VIDEO_COUNT }}
        run: python secure_main.py

