name: Auto YouTube Upload

on:
  schedule:
    - cron: '0 9 * * *'  # 매일 오전 9시 KST (UTC 기준 0시)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v3

    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: .env 설정
      run: |
        echo "ELEVENLABS_KEY=${{ secrets.ELEVENLABS_KEY }}" >> .env
        echo "ELEVENLABS_VOICE_ID=${{ secrets.ELEVENLABS_VOICE_ID }}" >> .env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
        echo "GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}" >> .env
        echo "GOOGLE_CLIENT_SECRET_JSON=${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}" >> .env
        echo "OPENAI_API_KEY_1=${{ secrets.OPENAI_API_KEY_1 }}" >> .env
        echo "OPENAI_API_KEY_2=${{ secrets.OPENAI_API_KEY_2 }}" >> .env
        echo "OPENAI_API_KEY_3=${{ secrets.OPENAI_API_KEY_3 }}" >> .env
        echo "OPENAI_API_KEY_4=${{ secrets.OPENAI_API_KEY_4 }}" >> .env
        echo "OPENAI_API_KEY_5=${{ secrets.OPENAI_API_KEY_5 }}" >> .env
        echo "OPENAI_API_KEY_6=${{ secrets.OPENAI_API_KEY_6 }}" >> .env
        echo "OPENAI_API_KEY_7=${{ secrets.OPENAI_API_KEY_7 }}" >> .env
        echo "OPENAI_API_KEY_8=${{ secrets.OPENAI_API_KEY_8 }}" >> .env
        echo "OPENAI_API_KEY_9=${{ secrets.OPENAI_API_KEY_9 }}" >> .env
        echo "OPENAI_API_KEY_10=${{ secrets.OPENAI_API_KEY_10 }}" >> .env

    - name: Python 스크립트 실행
      run: |
        python secure_main.py

