name: Auto YouTube Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 매일 한국 시간 12시 실행

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 최신 버전 사용

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python packages
      run: pip install -r requirements.txt

    - name: Create static directory
      run: mkdir -p static

    - name: Run Main Script
      env:
        # OpenAI API Keys (GitHub Secrets에 등록된 이름과 정확히 일치)
        OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
        OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
        OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
        OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
        OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
        OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
        OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
        OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
        OPENAI_API_KEY_9: ${{ secrets.OPENAI_API_KEY_9 }}
        OPENAI_API_KEY_10: ${{ secrets.OPENAI_API_KEY_10 }}
        # Google API Keys
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}          # 주의: Secrets 이름 변경!
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}  # 주의: Secrets 이름 변경!
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}  # 주의: Secrets 이름 변경!
      run: python secure_main.py
