name: YouTube AutoBot Pro

on:
  schedule:
    - cron: '0 */6 * * *'  # 6시간 간격 실행
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-24.04
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libgl1
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Automation
      env:
        OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }}
        ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: |
        mkdir -p static/{videos,thumbnails,audio}
        python secure_main.py --auto

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: youtube-results
        path: static/

