name: YouTube AutoBot 2.0

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # 6시간 간격 실행
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libsm6 libxext6

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Main Script
      env:
        ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }}
      run: |
        mkdir -p static/{videos,thumbnails,audio}
        python secure_main.py --auto

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: youtube-output
        path: |
          static/videos/*.mp4
          static/thumbnails/*.png

