name: Daily YouTube Upload

on:
  schedule:
    - cron: '0 10 * * *'  # 매일 한국 시간 19시 (UTC+9)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Create static folder
        run: |
          mkdir -p static
          curl -o static/bg.png https://via.placeholder.com/1280x720.png
          curl -o static/music.mp3 https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3

      - name: Run automation
        env:
          OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
          OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
          OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
          OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
          OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
          OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
          OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
          OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
          OPENAI_API_KEY_9: ${{ secrets.OPENAI_API_KEY_9 }}
          OPENAI_API_KEY_10: ${{ secrets.OPENAI_API_KEY_10 }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: python secure_main.py

