name: YouTube AutoBot

on:
  schedule:
    - cron: '0 0,12 * * *'  # 하루 2회 실행 (00:00, 12:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg imagemagick fonts-dejavu

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Main Script
      env:
        ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
        ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
        OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
        OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
        OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
        OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
        OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
        OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
        OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
        OPENAI_API_KEY_9: ${{ secrets.OPENAI_API_KEY_9 }}
        OPENAI_API_KEY_10: ${{ secrets.OPENAI_API_KEY_10 }}
      run: |
        python secure_main.py --auto

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: |
          static/videos/*.mp4
          static/thumbnails/*.jpg

