name: YouTube AutoBot Pro Ultra

on:
  schedule:
    - cron: '0 */6 * * *'  # 6시간 간격 실행
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create directories
      run: |
        mkdir -p static/{videos,audio,thumbnails,logs}

    - name: Run AutoBot
      env:
        ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
        ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
        OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }}
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        YOUTUBE_CLIENT_SECRETS_JSON: ${{ secrets.YOUTUBE_CLIENT_SECRETS_JSON }}
      run: |
        python secure_main.py --auto --max-videos 3
