name: Upload YouTube Video

on:
  schedule:
    - cron: '0 * * * *'  # 매 시간마다 실행
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai google-api-python-client pytrends elevenlabs

      - name: Install FFmpeg & ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg imagemagick -y

      - name: Run Script
        env:
          OPENAI_API_KEY_1: ${{ secrets.OPENAI_API_KEY_1 }}
          OPENAI_API_KEY_2: ${{ secrets.OPENAI_API_KEY_2 }}
          OPENAI_API_KEY_3: ${{ secrets.OPENAI_API_KEY_3 }}
          OPENAI_API_KEY_4: ${{ secrets.OPENAI_API_KEY_4 }}
          OPENAI_API_KEY_5: ${{ secrets.OPENAI_API_KEY_5 }}
          OPENAI_API_KEY_6: ${{ secrets.OPENAI_API_KEY_6 }}
          OPENAI_API_KEY_7: ${{ secrets.OPENAI_API_KEY_7 }}
          OPENAI_API_KEY_8: ${{ secrets.OPENAI_API_KEY_8 }}
          OPENAI_API_KEY_9: ${{ secrets.OPENAI_API_KEY_9 }}
          OPENAI_API_KEY_10: ${{ secrets.OPENAI_API_KEY_10 }}
          ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: python secure_main.py

