name: Advanced Auto Upload
on:
  schedule:
    - cron: "0 8,12,16,20 * * *"  # 4회/일 실행
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Execute Bot
        env:
          OPENAI_KEYS: ${{ secrets.OPENAI_KEYS }}
          ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.VOICE_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CSECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_RTOKEN }}
          TREND_KEYWORDS: ${{ secrets.TRENDS }}
          DAILY_VIDEOS: ${{ secrets.DAILY_COUNT }}
        run: python main.py

