name: Upload YouTube Video

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 6시간마다 실행

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run uploader
        env:
          OPENAI_API_KEYS: ${{ secrets.OPENAI_API_KEYS }}
          ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          python secure_main.py --auto --max-videos 2

